
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: snowflake_customer_purchases
    description: this is the toal purchases for each customer in snowflake sample data
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
